[goldmark]
  [goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
  [goldmark.extensions]
    typographer = false

# Table of contents
# Add toc = true to content front matter to enable
[tableOfContents]
  endLevel   = 5
  ordered    = false
  startLevel = 3