[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.1"

[context.production]
  command = """
  hugo
  npm i @torchlight-api/torchlight-cli
  npx torchlight
  """

[context.preview]
  command = """
  hugo --environment preview
  npm i @torchlight-api/torchlight-cli
  npx torchlight
  """
  [[headers]]
    for = "/*"
      [headers.values]
      X-Robots-Tag = "noindex"

[context.drafts]
  command = """
  hugo --environment drafts -D
  npm i @torchlight-api/torchlight-cli
  npx torchlight
  """
  [[headers]]
    for = "/*"
      [headers.values]
      X-Robots-Tag = "noindex"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404